# Generated by Django 5.1.4 on 2024-12-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('sold_to', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('salesperson', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(choices=[('Armada', 'Armada'), ('Legacy', 'Legacy'), ('Main', 'Main'), ('Premiere', 'Premiere')], max_length=255)),
                ('transaction_type', models.CharField(choices=[('OUT', 'OUT'), ('IN', 'IN')], max_length=3)),
                ('qty', models.PositiveIntegerField()),
                ('brand', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c')], max_length=1)),
                ('size', models.IntegerField(choices=[(15, 15), (16, 16), (17, 17)])),
                ('model', models.CharField(choices=[('d', 'd'), ('e', 'e'), ('f', 'f')], max_length=1)),
                ('specs', models.CharField(choices=[('q', 'q'), ('r', 'r'), ('s', 's')], max_length=1)),
                ('load', models.CharField(blank=True, choices=[('q1', 'q1'), ('r1', 'r1'), ('s1', 's1')], max_length=3, null=True)),
                ('supplier', models.CharField(blank=True, choices=[('RC', 'RC'), ('ENT', 'ENT'), ('SP', 'SP'), ('YHI', 'YHI'), ('PWG', 'PWG')], max_length=3, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
