# Generated by Django 5.1.4 on 2024-12-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_transaction_load_alter_transaction_model_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Tire',
        ),
        migrations.AlterModelOptions(
            name='tire',
            options={'verbose_name': 'Tire', 'verbose_name_plural': 'Tires'},
        ),
    ]
