# Generated by Django 5.1.4 on 2024-12-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_transaction_tire_alter_tire_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='brand',
            field=models.CharField(choices=[('BFGoodrich', 'BFGoodrich'), ('Michelin', 'Michelin'), ('Bridgestone', 'Bridgestone'), ('Lexani', 'Lexani'), ('Wanli', 'Wanli'), ('Toyo', 'Toyo'), ('Dunlop', 'Dunlop'), ('Cooper', 'Cooper'), ('Vredestein', 'Vredestein'), ('Nitto', 'Nitto')], max_length=100),
        ),
    ]
