# Generated by Django 5.1.4 on 2024-12-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_tire_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='remarks',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
