# Generated by Django 5.1.4 on 2024-12-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_magwheel_brand_alter_magwheel_holebore_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magwheel',
            old_name='holebore',
            new_name='bore',
        ),
        migrations.AlterField(
            model_name='magwheel',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
