# Generated by Django 5.1.4 on 2024-12-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_holebore_magwheel_bore_alter_magwheel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='invoice_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
