# Generated by Django 5.1.4 on 2025-06-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_transaction_notes_transaction_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transactionpayment',
            name='credit_card_type',
            field=models.CharField(blank=True, choices=[('BDO Striaght', 'BDO Striaght'), ('BDO 3mos', 'BDO 3mos'), ('BDO 6mos', 'BDO 6mos'), ('BDO 12mos', 'BDO 12mos'), ('BDO 24mos', 'BDO 24mos'), ('BPI Striaght', 'BPI Striaght'), ('BPI 3mos', 'BPI 3mos'), ('BPI 6mos', 'BPI 6mos'), ('BPI 12mos', 'BPI 12mos'), ('BPI 24mos', 'BPI 24mos'), ('MetroBank Striaght', 'MetroBank Striaght'), ('MetroBank 3mos', 'MetroBank 3mos'), ('MetroBank 6mos', 'MetroBank 6mos'), ('MetroBank 12mos', 'MetroBank 12mos'), ('MetroBank 24mos', 'MetroBank 24mos')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpayment',
            name='debit_card_bank',
            field=models.CharField(blank=True, choices=[('BDO Striaght', 'BDO Striaght'), ('BDO 3mos', 'BDO 3mos'), ('BDO 6mos', 'BDO 6mos')], max_length=50, null=True),
        ),
    ]
