# Generated by Django 5.1.4 on 2024-12-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='load',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='specs',
            field=models.CharField(max_length=255),
        ),
    ]
