# Generated by Django 5.1.4 on 2024-12-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_tire_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magwheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('sold_to', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('salesperson', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(choices=[('Armada', 'Armada'), ('Legacy', 'Legacy'), ('Main', 'Main'), ('Premiere', 'Premiere')], max_length=255)),
                ('transaction_type', models.CharField(choices=[('OUT', 'OUT'), ('IN', 'IN')], max_length=3)),
                ('qty', models.PositiveIntegerField()),
                ('brand', models.CharField(choices=[('BFGoodrich', 'BFGoodrich'), ('Michelin', 'Michelin'), ('Bridgestone', 'Bridgestone'), ('Lexani', 'Lexani'), ('Wanli', 'Wanli'), ('Toyo', 'Toyo'), ('Dunlop', 'Dunlop'), ('Cooper', 'Cooper'), ('Vredestein', 'Vredestein'), ('Nitto', 'Nitto')], max_length=100)),
                ('size', models.CharField(max_length=5)),
                ('model', models.CharField(max_length=255)),
                ('pcd1', models.CharField(max_length=10)),
                ('pcd2', models.CharField(blank=True, max_length=10, null=True)),
                ('offset', models.IntegerField()),
                ('holebore', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(max_length=255)),
                ('supplier', models.CharField(blank=True, choices=[('RC', 'RC'), ('ENT', 'ENT'), ('SP', 'SP'), ('YHI', 'YHI'), ('PWG', 'PWG')], max_length=3, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Magwheel',
                'verbose_name_plural': 'Magwheels',
            },
        ),
    ]
