# Generated by Django 5.1.4 on 2024-12-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_magwheel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magwheel',
            name='brand',
            field=models.CharField(choices=[('Ultra', 'Ultra'), ('Walker Evans', 'Walker Evans'), ('Worx', 'Worx'), ('Platinum', 'Platinum'), ('Focal', 'Focal'), ('Savini', 'Savini'), ('Lexani', 'Lexani'), ('XXR', 'XXR'), ('Armada', 'Armada')], max_length=100),
        ),
        migrations.AlterField(
            model_name='magwheel',
            name='holebore',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='magwheel',
            name='offset',
            field=models.CharField(max_length=10),
        ),
    ]
