# Generated by Django 5.1.4 on 2024-12-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_tire_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magwheel',
            name='invoice_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
