# Generated by Django 5.1.4 on 2025-01-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_magwheel_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magwheel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tire',
            name='date',
            field=models.DateField(),
        ),
    ]
