# Generated by Django 5.1.4 on 2025-01-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_magwheel_date_alter_tire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magwheel',
            name='bore',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='magwheel',
            name='invoice_number',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='magwheel',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='magwheel',
            name='pcd2',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='magwheel',
            name='salesperson',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='magwheel',
            name='sold_to',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='magwheel',
            name='supplier',
            field=models.CharField(blank=True, choices=[('RC', 'RC'), ('ENT', 'ENT'), ('SP', 'SP'), ('YHI', 'YHI'), ('PWG', 'PWG')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='invoice_number',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='load',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='salesperson',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='sold_to',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='supplier',
            field=models.CharField(blank=True, choices=[('RC', 'RC'), ('ENT', 'ENT'), ('SP', 'SP'), ('YHI', 'YHI'), ('PWG', 'PWG')], default='', max_length=3, null=True),
        ),
    ]
