# Generated by Django 5.1.4 on 2025-06-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_magwheel_bore_alter_magwheel_invoice_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magwheel_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('brand', models.CharField(choices=[('Ultra', 'Ultra'), ('Walker Evans', 'Walker Evans'), ('Worx', 'Worx'), ('Platinum', 'Platinum'), ('Focal', 'Focal'), ('Savini', 'Savini'), ('Lexani', 'Lexani'), ('XXR', 'XXR'), ('Armada', 'Armada'), ('RBP', 'RBP'), ('ROGUE', 'ROGUE'), ('LRG', 'LRG'), ('PROCOMP', 'PROCOMP'), ('SOTA', 'SOTA'), ('SPEC1', 'SPEC1'), ('CAVALLO', 'CAVALLO'), ('XF FORGED', 'XF FORGED'), ('BLADE', 'BLADE'), ('', '')], max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=255)),
                ('pcd1', models.CharField(max_length=10)),
                ('pcd2', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('offset', models.CharField(max_length=10)),
                ('bore', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('color', models.CharField(max_length=255)),
                ('supplier', models.CharField(blank=True, choices=[('RC', 'RC'), ('ENT', 'ENT'), ('SP', 'SP'), ('YHI', 'YHI'), ('PWG', 'PWG')], default='', max_length=3, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Magwheel',
                'verbose_name_plural': 'Magwheels',
            },
        ),
        migrations.CreateModel(
            name='Tire_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('brand', models.CharField(choices=[('BFGoodrich', 'BFGoodrich'), ('Michelin', 'Michelin'), ('Bridgestone', 'Bridgestone'), ('Lexani', 'Lexani'), ('Wanli', 'Wanli'), ('Toyo', 'Toyo'), ('Dunlop', 'Dunlop'), ('Cooper', 'Cooper'), ('Vredestein', 'Vredestein'), ('Nitto', 'Nitto')], max_length=100)),
                ('size', models.IntegerField()),
                ('model', models.CharField(max_length=255)),
                ('specs', models.CharField(max_length=255)),
                ('load', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=4, null=True)),
                ('supplier', models.CharField(blank=True, choices=[('RC', 'RC'), ('ENT', 'ENT'), ('SP', 'SP'), ('YHI', 'YHI'), ('PWG', 'PWG')], default='', max_length=3, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Tire',
                'verbose_name_plural': 'Tires',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(blank=True, default='', null=True)),
                ('sold_to', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date', models.DateField()),
                ('salesperson', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('location', models.CharField(choices=[('Armada', 'Armada'), ('Legacy', 'Legacy'), ('Main', 'Main'), ('Premiere', 'Premiere')], max_length=255)),
                ('transaction_type', models.CharField(choices=[('OUT', 'OUT'), ('IN', 'IN')], max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='magwheel',
            name='brand',
            field=models.CharField(choices=[('Ultra', 'Ultra'), ('Walker Evans', 'Walker Evans'), ('Worx', 'Worx'), ('Platinum', 'Platinum'), ('Focal', 'Focal'), ('Savini', 'Savini'), ('Lexani', 'Lexani'), ('XXR', 'XXR'), ('Armada', 'Armada'), ('RBP', 'RBP'), ('ROGUE', 'ROGUE'), ('LRG', 'LRG'), ('PROCOMP', 'PROCOMP'), ('SOTA', 'SOTA'), ('SPEC1', 'SPEC1'), ('CAVALLO', 'CAVALLO'), ('XF FORGED', 'XF FORGED'), ('BLADE', 'BLADE'), ('', '')], max_length=100),
        ),
    ]
