# Generated by Django 5.1.4 on 2025-06-21 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_magwheel_test_tire_test_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magwheel_test',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magwheels', to='inventory.transaction'),
        ),
        migrations.AddField(
            model_name='tire_test',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tires', to='inventory.transaction'),
        ),
    ]
