# Generated by Django 5.1.4 on 2025-06-22 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_magwheel_test_transaction_tire_test_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magwheel_test',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tire_test',
            options={},
        ),
    ]
