# Generated by Django 5.1.4 on 2025-06-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_transaction_price_alter_transaction_invoice_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='price',
        ),
        migrations.RemoveField(
            model_name='transactionpayment',
            name='reference',
        ),
        migrations.AddField(
            model_name='transactionpayment',
            name='cheque_on_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionpayment',
            name='credit_card_type',
            field=models.CharField(blank=True, choices=[('BDO Striaght', 'BDO Straight'), ('BDO 3mos', 'BDO 3mos'), ('BDO 6mos', 'BDO 6mos'), ('BDO 12mos', 'BDO 12mos'), ('BDO 24mos', 'BDO 24mos'), ('BPI Striaght', 'BPI Straight'), ('BPI 3mos', 'BPI 3mos'), ('BPI 6mos', 'BPI 6mos'), ('BPI 12mos', 'BPI 12mos'), ('BPI 24mos', 'BPI 24mos'), ('MetroBank Striaght', 'MetroBank Straight'), ('MetroBank 3mos', 'MetroBank 3mos'), ('MetroBank 6mos', 'MetroBank 6mos'), ('MetroBank 12mos', 'MetroBank 12mos'), ('MetroBank 24mos', 'MetroBank 24mos')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactionpayment',
            name='debit_card_bank',
            field=models.CharField(blank=True, choices=[('BDO', 'BDO'), ('BPI', 'BPI'), ('MetroBank', 'MetroBank')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactionpayment',
            name='locked',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='transactionpayment',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactionpayment',
            name='method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('GCash', 'GCash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('BDO Checkout', 'BDO Checkout'), ('Utang', 'Utang')], max_length=50),
        ),
    ]
