# Generated by Django 5.1.4 on 2025-06-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionpayment',
            name='method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('GCash', 'GCash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('BDO Checkout', 'BDO Checkout'), ('Receivables', 'Receivables'), ('Payables', 'Payables')], max_length=50),
        ),
    ]
