# Generated by Django 5.1.4 on 2025-06-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_transactionpayment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpayment',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='magwheel_test',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
