# Generated by Django 5.1.4 on 2025-06-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_transactionpayment_notes_alter_magwheel_test_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magwheel_test',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
