# Generated by Django 5.1.4 on 2025-06-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_magwheel_test_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.BooleanField(default=False),
        ),
    ]
