# Generated by Django 5.1.3 on 2025-06-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionpayment',
            name='debit_card_bank',
            field=models.CharField(blank=True, choices=[('BDO', 'BDO'), ('BPI', 'BPI'), ('MetroBank', 'MetroBank')], max_length=50, null=True),
        ),
    ]
