# Generated by Django 5.2.6 on 2025-09-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_transactionpayment_debit_card_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magwheel',
            name='brand',
            field=models.CharField(choices=[('Armada', 'Armada'), ('Blade', 'Blade'), ('Cavallo', 'Cavallo'), ('Focal', 'Focal'), ('LRG', 'LRG'), ('Lexani', 'Lexani'), ('Platinum', 'Platinum'), ('Procomp', 'Procomp'), ('RBP', 'RBP'), ('Rogue', 'Rogue'), ('Savini', 'Savini'), ('Sota', 'Sota'), ('Spec1', 'Spec1'), ('Ultra', 'Ultra'), ('Walker Evans', 'Walker Evans'), ('Worx', 'Worx'), ('XF Forged', 'XF Forged'), ('XXR', 'XXR')], max_length=100),
        ),
        migrations.AlterField(
            model_name='magwheel_test',
            name='brand',
            field=models.CharField(choices=[('Armada', 'Armada'), ('Blade', 'Blade'), ('Cavallo', 'Cavallo'), ('Focal', 'Focal'), ('LRG', 'LRG'), ('Lexani', 'Lexani'), ('Platinum', 'Platinum'), ('Procomp', 'Procomp'), ('RBP', 'RBP'), ('Rogue', 'Rogue'), ('Savini', 'Savini'), ('Sota', 'Sota'), ('Spec1', 'Spec1'), ('Ultra', 'Ultra'), ('Walker Evans', 'Walker Evans'), ('Worx', 'Worx'), ('XF Forged', 'XF Forged'), ('XXR', 'XXR')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tire',
            name='brand',
            field=models.CharField(choices=[('BFGoodrich', 'BFGoodrich'), ('Bridgestone', 'Bridgestone'), ('Cooper', 'Cooper'), ('Dunlop', 'Dunlop'), ('Lexani', 'Lexani'), ('Michelin', 'Michelin'), ('Nitto', 'Nitto'), ('Toyo', 'Toyo'), ('Vredestein', 'Vredestein'), ('Wanli', 'Wanli')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tire_test',
            name='brand',
            field=models.CharField(choices=[('BFGoodrich', 'BFGoodrich'), ('Bridgestone', 'Bridgestone'), ('Cooper', 'Cooper'), ('Dunlop', 'Dunlop'), ('Lexani', 'Lexani'), ('Michelin', 'Michelin'), ('Nitto', 'Nitto'), ('Toyo', 'Toyo'), ('Vredestein', 'Vredestein'), ('Wanli', 'Wanli')], max_length=100),
        ),
    ]
