# Generated by Django 5.2.6 on 2025-09-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_magwheel_brand_alter_magwheel_test_brand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Magwheel_test',
            new_name='MagwheelModel',
        ),
        migrations.RenameModel(
            old_name='Tire_test',
            new_name='TireModel',
        ),
        migrations.AlterField(
            model_name='tire',
            name='location',
            field=models.CharField(choices=[('Armada', 'Armada'), ('Legacy', 'Legacy'), ('Main', 'Main'), ('Premier', 'Premier')], max_length=255),
        ),
    ]
