# Generated by Django 5.2.6 on 2025-09-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_rename_magwheel_test_magwheelmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magwheel',
            name='brand',
            field=models.CharField(choices=[('Armada', 'Armada'), ('Blade', 'Blade'), ('Cavallo', 'Cavallo'), ('Focal', 'Focal'), ('LRG', 'LRG'), ('Lexani', 'Lexani'), ('Platinum', 'Platinum'), ('Procomp', 'Procomp'), ('RBP', 'RBP'), ('ROGUE ', 'ROGUE '), ('Rogue', 'Rogue'), ('Savini', 'Savini'), ('Sota', 'Sota'), ('Spec1', 'Spec1'), ('Ultra', 'Ultra'), ('Walker Evans', 'Walker Evans'), ('Worx', 'Worx'), ('XF Forged', 'XF Forged'), ('XXR', 'XXR')], max_length=100),
        ),
        migrations.AlterField(
            model_name='magwheelmodel',
            name='brand',
            field=models.CharField(choices=[('Armada', 'Armada'), ('Blade', 'Blade'), ('Cavallo', 'Cavallo'), ('Focal', 'Focal'), ('LRG', 'LRG'), ('Lexani', 'Lexani'), ('Platinum', 'Platinum'), ('Procomp', 'Procomp'), ('RBP', 'RBP'), ('ROGUE ', 'ROGUE '), ('Rogue', 'Rogue'), ('Savini', 'Savini'), ('Sota', 'Sota'), ('Spec1', 'Spec1'), ('Ultra', 'Ultra'), ('Walker Evans', 'Walker Evans'), ('Worx', 'Worx'), ('XF Forged', 'XF Forged'), ('XXR', 'XXR')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='location',
            field=models.CharField(choices=[('Armada', 'Armada'), ('Legacy', 'Legacy'), ('Main', 'Main'), ('Premier', 'Premier')], max_length=255),
        ),
        migrations.AlterField(
            model_name='transactionpayment',
            name='method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('BDO Checkout', 'BDO Checkout'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('GCash', 'GCash'), ('Payables', 'Payables'), ('Receivables', 'Receivables')], max_length=50),
        ),
    ]
