# Generated by Django 5.2.6 on 2025-09-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_magwheel_brand_alter_magwheelmodel_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magwheel',
            name='brand',
            field=models.CharField(choices=[('Armada', 'Armada'), ('Blade', 'Blade'), ('Cavallo', 'Cavallo'), ('Focal', 'Focal'), ('LRG', 'LRG'), ('Lexani', 'Lexani'), ('Platinum', 'Platinum'), ('Procomp', 'Procomp'), ('RBP', 'RBP'), ('Rogue', 'Rogue'), ('Savini', 'Savini'), ('Sota', 'Sota'), ('Spec1', 'Spec1'), ('Ultra', 'Ultra'), ('Walker Evans', 'Walker Evans'), ('Worx', 'Worx'), ('XF Forged', 'XF Forged'), ('XXR', 'XXR')], max_length=100),
        ),
        migrations.AlterField(
            model_name='magwheelmodel',
            name='brand',
            field=models.CharField(choices=[('Armada', 'Armada'), ('Blade', 'Blade'), ('Cavallo', 'Cavallo'), ('Focal', 'Focal'), ('LRG', 'LRG'), ('Lexani', 'Lexani'), ('Platinum', 'Platinum'), ('Procomp', 'Procomp'), ('RBP', 'RBP'), ('Rogue', 'Rogue'), ('Savini', 'Savini'), ('Sota', 'Sota'), ('Spec1', 'Spec1'), ('Ultra', 'Ultra'), ('Walker Evans', 'Walker Evans'), ('Worx', 'Worx'), ('XF Forged', 'XF Forged'), ('XXR', 'XXR')], max_length=100),
        ),
    ]
